version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trading_system
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: ${DB_PASSWORD:-trading123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trading_system"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and message queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Trading System
  trading-system:
    build: .
    environment:
      - DATABASE_URL=postgresql://trader:${DB_PASSWORD:-trading123}@postgres:5432/trading_system
      - REDIS_URL=redis://redis:6379
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - FMP_API_KEY=${FMP_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5000:5000"

  # Web Dashboard
  dashboard:
    build: .
    command: ["python", "dashboard/app.py"]
    environment:
      - FLASK_APP=dashboard/app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://trader:${DB_PASSWORD:-trading123}@postgres:5432/trading_system
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5001"
    profiles:
      - dashboard

volumes:
  postgres_data:
  redis_data: 